* PL Catalog

A catalogue of languages, environments, and tooling around them.

* Languages

** [[https://github.com/mukul-rathi/bolt][Bolt]]
Bolt is a language with in-built data-race freedom! 

** [[https://github.com/souffle-lang/souffle][Souffle]]
Soufflé is a variant of Datalog for tool designers crafting analyses in Horn clauses. Soufflé synthesizes a native parallel C++ program from a logic specification. 

** [[https://github.com/catseye/Mascarpone][Mascarpone]]
Mascarpone is a self-modifying programming language in the style of Emmental.

** [[https://github.com/samrushing/irken-compiler][Irken]]
Irken is a strongly typed, compiled language with a lisp-like syntax extensible with macros.
It uses type inference along with a powerful type system to give you the speed of a compiled language with high-level data types and a higher degree of safety than languages like C/C++.

** [[https://github.com/urweb/urweb][Ur/Web]]
Ur is a programming language in the tradition of ML and Haskell, but featuring a significantly richer type system. Ur is functional, pure, statically typed, and strict. Ur supports a powerful kind of metaprogramming based on row types.

** [[https://github.com/darklang/][Dark]]
Dark, a combined language, editor, and infrastructure to make it easy to build backends.

** [[https://github.com/teyjus/teyjus][Teyjus]]
An efficient implementation of the higher-order logic programming language Lambda Prolog

** [[https://github.com/pikelet-lang/pikelet/][Pikelet]]

** [[https://github.com/opencypher/][Open Cypher]]
A declarative property graph query language

** [[https://github.com/ballesta25/Morpheus][Morpheus]]
A stack-based programming language with derivational morphemes 

** [[https://github.com/koka-lang/koka][Koka]]
Koka: a function-oriented language with effect inference

** [[https://github.com/red/red][Red]]
Red is a new programming language strongly inspired by Rebol, but with a broader field of usage thanks to its native-code compiler, from system programming to high-level scripting, while providing modern support for concurrency and multi-core CPUs.

** [[https://github.com/marcobambini/gravity][Gravity]]
Gravity is a powerful, dynamically typed, lightweight, embeddable programming language written in C without any external dependencies (except for stdlib). It is a class-based concurrent scripting language with modern Swift-like syntax.

** [[https://github.com/ballerina-platform/ballerina-lang][Ballerina]]
Ballerina is an open source programming language and platform for cloud-era application programmers to easily write software that just works.

** [[https://github.com/gluon-lang/gluon][Gluon]]
A static, type inferred and embeddable language written in Rust.

** [[https://github.com/gleam-lang/gleam][Gleam]]
A statically typed language for the Erlang VM

** [[https://github.com/astrolang/astro][Astro]]
A fun safe language for rapid prototyping and high performance applications

** [[https://github.com/felix-lang/felix][Felix]]
An advanced, statically typed, high performance scripting language with native C++ embedding.

** [[https://github.com/wyvernlang/wyvern][Wyvern]]
Wyvern is a new general-purpose programming language designed to support adaptation and assurance.

** [[https://github.com/slovnicki/pLam][pLam]]
An interpreter for learning and exploring pure λ-calculus

** [[https://github.com/topshell-language/topshell][TopShell]]
Purely functional, reactive scripting language

** [[https://github.com/FStarLang/FStar][FStar]]
Verification system for effectful programs

** [[https://github.com/agda/agda][Agda]]
Agda is a dependently typed programming language / interactive theorem prover.

** [[https://github.com/factor/factor][Factor]]
Factor is a concatenative, stack-based programming language with high-level features including dynamic types, extensible syntax, macros, and garbage collection. On a practical side, Factor has a full-featured library, supports many different platforms, and has been extensively documented.

** [[https://github.com/evincarofautumn/kitten][Kitten]]
A statically typed concatenative systems programming language.

* Environments

** [[https://github.com/jamii/imp][Imp]]
Relational Programming Environment

** [[https://github.com/enso-org/][Enso]]
Enso – a visual and textual functional programming language.

** [[https://github.com/unisonweb/unison][Unison]]
Unison is a modern, statically-typed purely functional language, similar to Haskell, but with the ability to describe entire distributed systems with a single program.

** [[https://github.com/supercollider/supercollider][SuperCollider]]
An audio server, programming language, and IDE for sound synthesis and algorithmic composition. 

* Tooling

** [[https://github.com/nanocaml/nanocaml][NanoCaml]]

** [[https://github.com/RobertHarper/TILT-Compiler][TILT]]
TILT is a compiler for Standard ML that uses Typed Intermediate
Languages.

** [[https://github.com/mfranzs/typer-piper][Typer Piper]]
The Typer Piper: Automating Data Structure Transformations Through Type Chaining

** [[https://github.com/vriad/zod][Zod]]
Zod is a TypeScript-first schema declaration and validation library. I'm using the term "schema" to broadly refer to any data type/structure, from a simple string to a complex nested object.

** [[https://github.com/Matechs-Garage/matechs-effect][Matechs Effect]]
A Fully-fledged functional effect system for typescript with a rich standard library.

** [[https://github.com/dorchard/effects-as-sessions][Effects as Session]]
Formalised embedding of an imperative language with effect system into session-typed pi calculus.

** [[https://github.com/goldfirere/singletons][Singletons]]
Fake dependent types in Haskell using singletons 

** [[https://github.com/robotlolita/tamago][Tamago]]
A safe, extensible, layered programming language that runs on top of JavaScript 

** [[https://github.com/tweag/asterius][Asterius]]
Asterius is a Haskell to WebAssembly compiler based on GHC.

